### PR TITLE
fix: colours in `diff` codeblock

### PR DESCRIPTION
**Pull request by CoralPink**
Hello!!
I always use mdbook-catppuccin! 🐈‍⬛

After updating to `v1.0.0`, I noticed that the color theme is not applied correctly to the `diff`.

All we are doing in this PR is reverting the parameters related to diffs back to what they were before `v1.0.0`, but I think this will fix this issue.

Could you please confirm this?

Thanks!! ☕

### CODE REVIEW

**Review by nekowinston — DISMISSED** [review]
Hey, thanks for the PR. 
This is an issue with the highlightjs port that got [fixed recently](https://github.com/catppuccin/highlightjs/releases/tag/v0.1.3).
The files you edited are generated, please don't edit them; we just need to bump the `@catppuccin/highlightjs` dependency.

**Comment by CoralPink** [comment]
Ah, I see. I'm beginning to understand!

Is it my understanding that this can be solved by simply rewriting `pallete/package.json`?

I'm not sure if my understanding is correct, as I can't get the build to work in my local environment...

```sh
> catppuccin-mdbook@1.0.0 build
> sass -I node_modules --no-charset --no-source-map catppuccin.scss:../src/bin/assets/catppuccin.css catppuccin-admonish.scss:../src/bin/assets/catppuccin-admonish.css

Error: Can't find stylesheet to import.
  ╷
1 │ @use "@catppuccin/palette/scss/catppuccin" as catppuccin;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  catppuccin.scss 1:1  root stylesheet

Error: Can't find stylesheet to import.
  ╷
3 │ @use "@catppuccin/palette/scss/catppuccin" as catppuccin;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  catppuccin-admonish.scss 3:1  root stylesheet
```

**Comment by CoralPink** [comment]
Sorry, this was because I did not `npm install`.

Also, looking closer, maybe the package is supposed to be updated on release.

Sorry for the strange English!
You can also dismiss this PR if it gets in the way!

**Review by nekowinston — COMMENTED** [review]
No worries, thanks for adjusting the PR! I think that should be it.

**Comment by sgoudham** [comment]
Hey there :wave:, thanks for the pull request!

The changes with the dependency bump look good, could you just help me understand why https://github.com/catppuccin/mdBook/commit/051a7ff0a01f36e43750417f659328bc2f81e31d was reverted in [`1d10d5b` (#67)](https://github.com/catppuccin/mdBook/pull/67/commits/1d10d5bb9230cb2fe8bd368f3ab44ecb042c9ebf)? I specified the files because using `.` was copying over the `node_modules` directory into the source directory which wasn't great when it came time to `cargo publish`.

**Comment by CoralPink** [comment]
Sorry for repeating myself...

In the revert, I thought I had only undone the operations I had done, but I may have been wrong.

I'm getting kind of confused....

This is a very selfish question, but what should I do in this case...?

**Comment by CoralPink** [comment]
I have tried many things,

The `cappuccin.css` seems to match the one generated via
`npm run build` and the current one (which I manually rewrote).

Now all I have to do is fix the mistake in `package.json`?

...Please squash the messy commit history 😖

**Review by sgoudham — APPROVED** [review]
No need to apologise and don't worry about the commit history! 

I tested out the PR locally and it looks great! I appreciate you spending the time and effort to contribute to this repo :heart:

**Comment by CoralPink** [comment]
Thanks for the kind words!

I was actually in a hurry for nothing as I was doing it in the time before bed....

It was a good experience 😅
Thanks again 🩷

**Pull request merged**
